/**
 */
package McpMM.provider;

import McpMM.util.McpMMAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class McpMMItemProviderAdapterFactory extends McpMMAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public McpMMItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.ServiceMCP} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceMCPItemProvider serviceMCPItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.ServiceMCP}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceMCPAdapter() {
		if (serviceMCPItemProvider == null) {
			serviceMCPItemProvider = new ServiceMCPItemProvider(this);
		}

		return serviceMCPItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.ServerMCP} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServerMCPItemProvider serverMCPItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.ServerMCP}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServerMCPAdapter() {
		if (serverMCPItemProvider == null) {
			serverMCPItemProvider = new ServerMCPItemProvider(this);
		}

		return serverMCPItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.Agente} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AgenteItemProvider agenteItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.Agente}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAgenteAdapter() {
		if (agenteItemProvider == null) {
			agenteItemProvider = new AgenteItemProvider(this);
		}

		return agenteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.Workflow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkflowItemProvider workflowItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.Workflow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkflowAdapter() {
		if (workflowItemProvider == null) {
			workflowItemProvider = new WorkflowItemProvider(this);
		}

		return workflowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.Contexto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContextoItemProvider contextoItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.Contexto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContextoAdapter() {
		if (contextoItemProvider == null) {
			contextoItemProvider = new ContextoItemProvider(this);
		}

		return contextoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.Propiedad} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropiedadItemProvider propiedadItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.Propiedad}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropiedadAdapter() {
		if (propiedadItemProvider == null) {
			propiedadItemProvider = new PropiedadItemProvider(this);
		}

		return propiedadItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.TareaFinal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TareaFinalItemProvider tareaFinalItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.TareaFinal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTareaFinalAdapter() {
		if (tareaFinalItemProvider == null) {
			tareaFinalItemProvider = new TareaFinalItemProvider(this);
		}

		return tareaFinalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.TareaInicial} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TareaInicialItemProvider tareaInicialItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.TareaInicial}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTareaInicialAdapter() {
		if (tareaInicialItemProvider == null) {
			tareaInicialItemProvider = new TareaInicialItemProvider(this);
		}

		return tareaInicialItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.Escritura} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EscrituraItemProvider escrituraItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.Escritura}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEscrituraAdapter() {
		if (escrituraItemProvider == null) {
			escrituraItemProvider = new EscrituraItemProvider(this);
		}

		return escrituraItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.Lectura} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LecturaItemProvider lecturaItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.Lectura}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLecturaAdapter() {
		if (lecturaItemProvider == null) {
			lecturaItemProvider = new LecturaItemProvider(this);
		}

		return lecturaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.OperacionMCP} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperacionMCPItemProvider operacionMCPItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.OperacionMCP}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperacionMCPAdapter() {
		if (operacionMCPItemProvider == null) {
			operacionMCPItemProvider = new OperacionMCPItemProvider(this);
		}

		return operacionMCPItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.TareaTransformacionDatos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TareaTransformacionDatosItemProvider tareaTransformacionDatosItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.TareaTransformacionDatos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTareaTransformacionDatosAdapter() {
		if (tareaTransformacionDatosItemProvider == null) {
			tareaTransformacionDatosItemProvider = new TareaTransformacionDatosItemProvider(this);
		}

		return tareaTransformacionDatosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.TareaLLM} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TareaLLMItemProvider tareaLLMItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.TareaLLM}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTareaLLMAdapter() {
		if (tareaLLMItemProvider == null) {
			tareaLLMItemProvider = new TareaLLMItemProvider(this);
		}

		return tareaLLMItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.TareaUsuario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TareaUsuarioItemProvider tareaUsuarioItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.TareaUsuario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTareaUsuarioAdapter() {
		if (tareaUsuarioItemProvider == null) {
			tareaUsuarioItemProvider = new TareaUsuarioItemProvider(this);
		}

		return tareaUsuarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.TareaAnalisis} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TareaAnalisisItemProvider tareaAnalisisItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.TareaAnalisis}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTareaAnalisisAdapter() {
		if (tareaAnalisisItemProvider == null) {
			tareaAnalisisItemProvider = new TareaAnalisisItemProvider(this);
		}

		return tareaAnalisisItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.TareaEnvioContexto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TareaEnvioContextoItemProvider tareaEnvioContextoItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.TareaEnvioContexto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTareaEnvioContextoAdapter() {
		if (tareaEnvioContextoItemProvider == null) {
			tareaEnvioContextoItemProvider = new TareaEnvioContextoItemProvider(this);
		}

		return tareaEnvioContextoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.TareaRecepcionContexto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TareaRecepcionContextoItemProvider tareaRecepcionContextoItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.TareaRecepcionContexto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTareaRecepcionContextoAdapter() {
		if (tareaRecepcionContextoItemProvider == null) {
			tareaRecepcionContextoItemProvider = new TareaRecepcionContextoItemProvider(this);
		}

		return tareaRecepcionContextoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link McpMM.TareaServerMCP} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TareaServerMCPItemProvider tareaServerMCPItemProvider;

	/**
	 * This creates an adapter for a {@link McpMM.TareaServerMCP}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTareaServerMCPAdapter() {
		if (tareaServerMCPItemProvider == null) {
			tareaServerMCPItemProvider = new TareaServerMCPItemProvider(this);
		}

		return tareaServerMCPItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (serviceMCPItemProvider != null) serviceMCPItemProvider.dispose();
		if (serverMCPItemProvider != null) serverMCPItemProvider.dispose();
		if (agenteItemProvider != null) agenteItemProvider.dispose();
		if (workflowItemProvider != null) workflowItemProvider.dispose();
		if (contextoItemProvider != null) contextoItemProvider.dispose();
		if (propiedadItemProvider != null) propiedadItemProvider.dispose();
		if (tareaFinalItemProvider != null) tareaFinalItemProvider.dispose();
		if (tareaInicialItemProvider != null) tareaInicialItemProvider.dispose();
		if (escrituraItemProvider != null) escrituraItemProvider.dispose();
		if (lecturaItemProvider != null) lecturaItemProvider.dispose();
		if (operacionMCPItemProvider != null) operacionMCPItemProvider.dispose();
		if (tareaTransformacionDatosItemProvider != null) tareaTransformacionDatosItemProvider.dispose();
		if (tareaLLMItemProvider != null) tareaLLMItemProvider.dispose();
		if (tareaUsuarioItemProvider != null) tareaUsuarioItemProvider.dispose();
		if (tareaAnalisisItemProvider != null) tareaAnalisisItemProvider.dispose();
		if (tareaEnvioContextoItemProvider != null) tareaEnvioContextoItemProvider.dispose();
		if (tareaRecepcionContextoItemProvider != null) tareaRecepcionContextoItemProvider.dispose();
		if (tareaServerMCPItemProvider != null) tareaServerMCPItemProvider.dispose();
	}

}
