#

pluginName = McpMM Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_ServiceMCP_type = Service MCP
_UI_ServerMCP_type = Server MCP
_UI_Agente_type = Agente
_UI_Workflow_type = Workflow
_UI_Contexto_type = Contexto
_UI_Propiedad_type = Propiedad
_UI_Tarea_type = Tarea
_UI_TareaEjecutable_type = Tarea Ejecutable
_UI_TareaFinal_type = Tarea Final
_UI_TareaInicial_type = Tarea Inicial
_UI_Accion_type = Accion
_UI_Escritura_type = Escritura
_UI_Lectura_type = Lectura
_UI_OperacionMCP_type = Operacion MCP
_UI_TareaTransformacionDatos_type = Tarea Transformacion Datos
_UI_TareaLLM_type = Tarea LLM
_UI_TareaUsuario_type = Tarea Usuario
_UI_TareaAnalisis_type = Tarea Analisis
_UI_TareaEnvioContexto_type = Tarea Envio Contexto
_UI_TareaRecepcionContexto_type = Tarea Recepcion Contexto
_UI_TareaServerMCP_type = Tarea Server MCP
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_ServiceMCP_nombreServicio_feature = Nombre Servicio
_UI_ServiceMCP_servermcp_feature = Servermcp
_UI_ServiceMCP_agente_feature = Agente
_UI_ServiceMCP_workflow_feature = Workflow
_UI_ServerMCP_nombreServer_feature = Nombre Server
_UI_ServerMCP_operacionmcp_feature = Operacionmcp
_UI_Agente_nombreAgente_feature = Nombre Agente
_UI_Agente_numTareas_feature = Num Tareas
_UI_Agente_realiza_feature = Realiza
_UI_Workflow_nombreWorkflow_feature = Nombre Workflow
_UI_Workflow_contexto_feature = Contexto
_UI_Workflow_tarea_feature = Tarea
_UI_Workflow_empiezaCon_feature = Empieza Con
_UI_Workflow_finalizaCon_feature = Finaliza Con
_UI_Contexto_nombreContexto_feature = Nombre Contexto
_UI_Contexto_propiedad_feature = Propiedad
_UI_Contexto_esApuntadoPor_feature = Es Apuntado Por
_UI_Propiedad_nombrePropiedad_feature = Nombre Propiedad
_UI_Propiedad_tipoPropiedad_feature = Tipo Propiedad
_UI_Propiedad_esUsada_feature = Es Usada
_UI_Tarea_nombreTarea_feature = Nombre Tarea
_UI_Tarea_accion_feature = Accion
_UI_Tarea_precede_feature = Precede
_UI_Tarea_sigue_feature = Sigue
_UI_Tarea_precedeElse_feature = Precede Else
_UI_Tarea_agenteAsignado_feature = Agente Asignado
_UI_TareaEjecutable_idTarea_feature = Id Tarea
_UI_TareaEjecutable_descTarea_feature = Desc Tarea
_UI_TareaFinal_finaliza_feature = Finaliza
_UI_TareaInicial_empieza_feature = Empieza
_UI_Accion_nombreAccion_feature = Nombre Accion
_UI_Accion_apunta_feature = Apunta
_UI_Accion_usa_feature = Usa
_UI_OperacionMCP_nombreOperacion_feature = Nombre Operacion
_UI_OperacionMCP_descOperacion_feature = Desc Operacion
_UI_OperacionMCP_esEjecutadaOperacion_feature = Es Ejecutada Operacion
_UI_TareaTransformacionDatos_prompt_feature = Prompt
_UI_TareaLLM_prompt_feature = Prompt
_UI_TareaAnalisis_sigueElse_feature = Sigue Else
_UI_TareaAnalisis_prompt_feature = Prompt
_UI_TareaServerMCP_ejecutaOperacion_feature = Ejecuta Operacion
_UI_TareaServerMCP_prompt_feature = Prompt
_UI_Unknown_feature = Unspecified

_UI_TipoContexto_ENTERO_literal = ENTERO
_UI_TipoContexto_CADENA_literal = CADENA
_UI_TipoContexto_REAL_literal = REAL
_UI_TipoContexto_BOOLEANO_literal = BOOLEANO
_UI_TipoContexto_TEXTO_EXTENSO_literal = TEXTO_EXTENSO
_UI_TipoContexto_ARCHIVO_literal = ARCHIVO
_UI_TipoContexto_COLECCION_ARCHIVOS_literal = COLECCION_ARCHIVOS
_UI_TareaEnvioContexto_enviaA_feature = Envia A
_UI_TareaEnvioContexto_envioAsociado_feature = Envio Asociado
_UI_TareaRecepcionContexto_recibeDe_feature = Recibe De
_UI_TareaRecepcionContexto_recepcionAsociada_feature = Recepcion Asociada
