pluginName=McpMM Plugin
providerName=Sample Plugin Provider, Inc

editorName=McpMM Diagram Editing
context.description=McpMM Diagram Editing
context.name=In McpMM Diagram Editor
newWizardName=McpMM Diagram
newWizardDesc=Creates McpMM diagram.

initDiagramActionLabel=Initialize mcpmm_diagram diagram file


navigatorContentName=*.mcpmm_diagram diagram contents
domainNavigatorContentName=*.mcpmm model contents
update.diagram.name=Update McpMM diagram
update.diagram.description=Perform McpMM diagram update


# Property Sheet
tab.appearance=Appearance
tab.diagram=Rulers & Grid
tab.domain=Core

# Preferences
prefpage.ProyectoMCP.diagram.general=McpMM Diagram
prefpage.ProyectoMCP.diagram.appearance=Appearance
prefpage.ProyectoMCP.diagram.connections=Connections
prefpage.ProyectoMCP.diagram.printing=Printing
prefpage.ProyectoMCP.diagram.rulersAndGrid=Rulers And Grid


# Providers
metatype.name.ServiceMCP_1000=Undefined
metatype.name.Agente_2001=Agente
metatype.name.ServerMCP_2002=ServerMCP
metatype.name.Workflow_3001=Workflow
metatype.name.TareaTransformacionDatos_3002=TareaTransformacionDatos
metatype.name.Escritura_3003=Escritura
metatype.name.Lectura_3004=Lectura
metatype.name.TareaLLM_3005=TareaLLM
metatype.name.TareaUsuario_3006=TareaUsuario
metatype.name.TareaAnalisis_3007=TareaAnalisis
metatype.name.TareaEnvioContexto_3008=TareaEnvioContexto
metatype.name.TareaRecepcionContexto_3009=TareaRecepcionContexto
metatype.name.TareaServerMCP_3010=TareaServerMCP
metatype.name.Inicio_3011=Inicio
metatype.name.Final_3012=Final
metatype.name.Contexto_3013=Contexto
metatype.name.Propiedad_3014=Propiedad
metatype.name.OperacionMCP_3015=OperacionMCP
metatype.name.TareaSigue_4001=Undefined
metatype.name.TareaAnalisisSigueElse_4002=Undefined
metatype.name.TareaServerMCPEjecutaOperacion_4003=Undefined

# Commands and menu actions
cmdcategory.name=McpMM Editor Commands
cmdcategory.desc=McpMM Editor Commands

