pluginName=McpMM Plugin
providerName=Sample Plugin Provider, Inc

editorName=McpMM Diagram Editing
context.description=McpMM Diagram Editing
context.name=In McpMM Diagram Editor
newWizardName=McpMM Diagram
newWizardDesc=Creates McpMM diagram.

initDiagramActionLabel=Initialize mcpmm_diagram diagram file


navigatorContentName=*.mcpmm_diagram diagram contents
domainNavigatorContentName=*.mcpmm model contents
update.diagram.name=Update McpMM diagram
update.diagram.description=Perform McpMM diagram update


# Property Sheet
tab.appearance=Appearance
tab.diagram=Rulers & Grid
tab.domain=Core

# Preferences
prefpage.ProyectoMCP.diagram.general=McpMM Diagram
prefpage.ProyectoMCP.diagram.appearance=Appearance
prefpage.ProyectoMCP.diagram.connections=Connections
prefpage.ProyectoMCP.diagram.printing=Printing
prefpage.ProyectoMCP.diagram.rulersAndGrid=Rulers And Grid


# Providers
metatype.name.ServiceMCP_1000=Undefined
metatype.name.Agente_2001=Agente
metatype.name.ServerMCP_2002=ServerMCP
metatype.name.Workflow_2003=Workflow
metatype.name.Contexto_3001=Contexto
metatype.name.Propiedad_3002=Propiedad
metatype.name.OperacionMCP_3003=OperacionMCP
metatype.name.TareaTransformacionDatos_3004=TareaTransformacionDatos
metatype.name.Escritura_3005=Escritura
metatype.name.Lectura_3006=Lectura
metatype.name.TareaLLM_3007=TareaLLM
metatype.name.TareaUsuario_3008=TareaUsuario
metatype.name.TareaAnalisis_3009=TareaAnalisis
metatype.name.TareaEnvioContexto_3010=TareaEnvioContexto
metatype.name.TareaRecepcionContexto_3011=TareaRecepcionContexto
metatype.name.TareaServerMCP_3012=TareaServerMCP
metatype.name.Inicio_3013=Inicio
metatype.name.Final_3014=Final
metatype.name.AgenteTareas_4001=Undefined
metatype.name.TareaSigue_4002=Undefined
metatype.name.TareaAnalisisSigueElse_4003=Undefined
metatype.name.TareaServerMCPEjecutaOperacion_4004=Undefined

# Commands and menu actions
cmdcategory.name=McpMM Editor Commands
cmdcategory.desc=McpMM Editor Commands

